#!/bin/bash
exec 2>&1

{{#if bind.database ~}}
export CATALINA_OPTS="-DMONGODB_SERVICE_HOST={{bind.database.first.sys.ip}}
-DMONGODB_SERVICE_PORT={{bind.database.first.cfg.port}}
-DMONGODB_DATABASE={{cfg.mongodb_database}}"
{{/if ~}}

export JAVA_HOME="{{pkgPathFor "core/corretto"}}"
export TOMCAT_HOME="{{pkg.svc_var_path}}/tc"

exec ${TOMCAT_HOME}/bin/catalina.sh run