pool: henkhaus-forest
variables:
  - group: tf-backend-sa-pipeline
stages:

### STAGE 3 Test
- stage: Test_Red
  displayName: Test Red
  condition: eq(variables.run30Test, true)
  dependsOn: Deploy
  variables:
    a2AdminUser: null
    a2AdminPassword: null
    a2Token: null
    a2Url: null
    chefAutomatePublicIp: null
    chefAutomateServerPublicR53Dns: null
    haproxyPublicIp: null
    mongodbPublicIp: null
    nationalParksPublicIp: null
    permanentPeerPublicIp: null

  
  jobs:
  - job: inspec_testing
    displayName: "InSpec Testing"

    steps:
    - template: templates/agent-setup.yml
    - template: templates/test.yml
      parameters:
        color: "red" # set to a non-boolean value to have the build fail
    
   