pool: henkhaus-forest

steps:
- task: CmdLine@2
  inputs:
    script: |
      sudo yum -y install https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
      sudo yum install -y git unzip
  displayName: 'Install Dependencies'

- task: vsts-habitat-install@3
  displayName: 'Install Habitat'

- task: TerraformInstaller@0
  inputs:
    terraformVersion: '0.12.24'
  displayName: "Install Terraform"

- task: DownloadSecureFile@1
  inputs:
    secureFile: 'terraform.tfvars'
  displayName: 'Download terraform.tfvars'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aws'
    backendServiceAWS: 'AWS-ADO-Pipeline'
    backendAWSBucketName: 'sa-s3-tf-backend'
    backendAWSKey: 'terraform_state'
  displayName: "Terraform Init"

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aws'
    commandOptions: '-var-file=$(System.DefaultWorkingDirectory)/terraform.tfvars'
    environmentServiceNameAWS: 'AWS-ADO-Pipeline'

# # TERRAFORM DESTORY
# - task: TerraformTaskV1@0
#   inputs:
#     provider: 'aws'
#     command: 'destroy'
#     workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/aws'
#     environmentServiceNameAWS: 'AWS-ADO-Pipeline'
#   displayName: "Terraform Destroy"
