apiVersion: v1
kind: Secret
metadata:
  name: user-toml
type: Opaque
data:
  # Each item needs to be base64-encoded.
  # This overrides the port set in the Redis Habitat service.
  # Plain text content of the secret: "[mongod.net]\nbind_ip = '0.0.0.0'\n[mongod.security]\ncluster_auth_mode = ''"
  user.toml: W21vbmdvZC5uZXRdCmJpbmRfaXAgPSAnMC4wLjAuMCcKW21vbmdvZC5zZWN1cml0eV0KY2x1c3Rlcl9hdXRoX21vZGUgPSAnJwo=
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-db
customVersion: v1beta2
spec:
  v1beta2:
    # Make sure to update with your own origin and that you have published to Docker Hub
    image: scottford/mongodb
    count: 1
    service:
      name: mongodb
      # Name of the secret.
      # This is mounted inside of the pod as a user.toml file.
      configSecretName: user-toml
      topology: standalone
      group: default
---
apiVersion: habitat.sh/v1beta1
kind: Habitat
metadata:
  name: national-parks-app
customVersion: v1beta2
spec:
  v1beta2:
    # Make sure to update with your own origin and that you have published to Docker Hub
    image: ericheiser/national-parks
    count: 1
    service:
      name: national-parks
      topology: standalone
      bind:
        - name: database
          service: mongodb
          group: default
---
apiVersion: v1
kind: Service
metadata:
  name: national-parks
spec:
  selector:
    habitat-name: national-parks-app
  type: NodePort
  ports:
  - name: web
    nodePort: 30001
    port: 8080
    protocol: TCP
