
interval = 300

# Uncomment and replace values to report to Automate.
# This can also be applied at runtime via `hab config apply`
[reporter]
stdout = false
url = "${automate_url}"
token = "${automate_token}"